{
    "th06 Bomb Reimu A": "Spirit Sign \"Fantasy Seal\"",
    "th06 Bomb Reimu B": "Dream Sign \"Evil-Sealing Circle\"",
    "th06 Bomb Marisa A": "Magic Sign \"Stardust Reverie\"",
    "th06 Bomb Marisa B": "Love Sign \"Master Spark\"",
    "th06 config": "Customize ur Touhou EoSD: Momazos Diego",
    "th06 up": "Up ",
    "th06 down": "Down ",
    "th06 left": "Left ",
    "th06 right": "Right ",
    "th06 vertex": "Don't use the vertex buffer",
    "th06 fog": "Hate fog",
    "th06 16bit textures": "SMW Mario only",
    "th06 Gouraud shading": "Suppress use of Gouraud Shadow the Hedgehog",
    "th06 color composition": "Lesbian composition isn't applied to textures",
    "th06 rasterizer mode": "Start JoJo reference rasterizer mode",
    "th06 clear buffer": "Clear back buffer on refresh",
    "th06 minimum graphics": "Display minimum graphics needed",
    "th06 depth test": "Turn off the depth test",
    "th06 force frame": "Forcibly keep on 60 FPS",
    "th06 fullscreen": "Full screen",
    "th06 windowed": "Windowed",
    "th06 full rate": "1/1 (default)",
    "th06 half rate": "1/2",
    "th06 third rate": "1/3",
    "th06 32bits mode": "Normal",
    "th06 16bits mode": "SNES",
    "th06 accept": "Sure",
    "th06 cancel": "Abort",
    "th06 screen mode": "Screen mode",
    "th06 refresh rate": "Frameskip",
    "th06 colors": "Lesbian mode",
    "th06 pad X axis": "Pad X Axis (1–1000)",
    "th06 pad Y axis": "Pad Y Axis (1–1000)",
    "th06 check pad": "Check pad input",
    "th06 DirectInput": "Don't use the DirectInput pad",
    "th06 config saved caption": "Sure",
    "th06 config saved text": "Configuration saved.",
    "Stats Time Since Startup": "Time Since Windows XP Startup",
    "Stats Total Playtime": "Total Playtime (from Baldi's Basics)",
    "Stats Play Count": "Play Cunt",
    "Stats Clear Count": "Clear Cunt",
    "Stats Continue": "Credits",
    "Stats Practice": "Pro Tips",
    "Stats Retries": "Retries",
    "th06 Stats ReimuA": "Yukari Yakumo (Pepe)",
    "th06 Stats ReimuB": "Yukari Yakumo (Weeaboo)",
    "th06 Stats MarisaA": "Marisa Kirisame (True Pacifist Route)",
    "th06 Stats MarisaB": "Marisa Kirisame (Lesbian)",
    "th06": "Touhou EoSD: Momazos Diego",
    "th06_log_header": "Touhou Audit Log --------------------------------------------- \n",
    "th06_error_two_instances": "Cannot have two active instances.\n",
    "th06_log_tl_hal": "Working with T&L HAL.\n",
    "th06_log_directsound_init": "DirectSound was successfully initialized.\n",
    "th06_log_no_gamepad": "Unfortunately, no gamepad was found.\n",
    "th06_log_valid_pad": "A valid gamepad was found.\n",
    "th06_log_unable_to_read_file": "Cannot read the file %s.\n",
    "th06_log_directinput_init": "DirectInput was successfully initialized.\n",
    "th06_log_sound_file_read_error": "error: Sound file cannot be read. Check data %s.\n",
    "th06_log_texture_read_error": "Cannot read texture %s. Data is missing or corrupt.",
    "th06_log_sprite_read_error": "Cannot read sprite animation %s. Data is missing or corrupt.",
    "th06_log_export_failure": "Cannot overwrite file %s\n",
    "th06_log_read_only_full_disk": "Is the folder's read-only attribute set, or is the disk full?\n",
    "th06_log_reinit_corrupt_config": "The configuration file was corrupted, so it was reinitialized.\n",
    "th06_log_reinit_missing_config": "The configuration file was missing, so it was reinitialized.\n",
    "th06_log_first_startup_16bit": "Initial startup, initializing the screen in 16-bit mode.\n",
    "th06_log_first_startup_32bit": "Initial startup, initializing the screen in 32-bit mode.\n",
    "th06_log_character_init_failure": "error: Character initialization failure.\n",
    "th06_log_tl_hal_unavailable": "T&L HAL is unavailable.\n",
    "th06_log_hal_unavailable": "HAL is also unavailable.\n",
    "th06_log_backbuffer_nonlocking_suggestion": "Trying to make the backbuffer non-lockable.\n",
    "th06_log_direct3d_init_failure": "Failed to initialize Direct3D, the game cannot start.\n",
    "th06_log_refresh_rate": "Changing the refresh rate to 60Hz.\n",
    "th06_log_vertex": "Not using the vertex buffer.\n",
    "th06_log_fog": "Not using the fog.\n",
    "th06_log_16bit_textures": "Enforcing 16-bit textures.\n",
    "th06_log_Gouraud_shading": "Suppressing Gouraud shading.",
    "th06_log_color_composition": "Not applying color composition.\n",
    "th06_log_rasterizer_mode": "Starting in reference rasterizer mode.\n",
    "th06_log_clear_buffer": "Enforcing backbuffer clearing.\n",
    "th06_log_minimum_graphics": "Suppressing rendering items in-game.\n",
    "th06_log_depth_test": "Depth testing is turned off.\n",
    "th06_log_force_frame": "Forcibly maintaining 60FPS.\n",
    "th06_log_directinput_usage": "Not using DirectInput for pad or keyboard.\n",
    "th06_log_window_mode": "Running in windowed mode.\n",
}